controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 3
      - Revolute 4
      - Revolute 5
      - Revolute 6
      - Revolute 7
      - Revolute 8
      - Revolute 9
      - Revolute 10
      - Revolute 11
      - Revolute 12
      - Revolute 13
      - Revolute 14
      - Revolute 15
      - Revolute 16
      - Revolute 17
      - Revolute 18

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    gains:
      Revolute 1: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 2: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 3: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 4: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 5: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 6: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 7: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 8: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 9: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 10: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 11: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 12: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 13: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 14: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 15: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 16: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 17: {p: 10.0, i: 0.0, d: 0.1}
      Revolute 18: {p: 10.0, i: 0.0, d: 0.1}

